### ISSUE TITLE
Resolve TODOs or change into issues

### ISSUE THREAD

**Issue by skodapetr** [rdk/p2rank#14]
The p2rank code contains many TODOs, for a contributor they often do not fully explain what is needed or what is the severity of TODO. 

It would be better to remove them and rather create GitHub issues with a more detailed description (what, why, how .. ).

**Comment by rdk** [comment]
I agree about creating GitHub issues but strongly disagree about removing TODOs. Where possible they can be linked with issues by referencing the issue id.
