### ISSUE TITLE
readme.txt vs readme.md

### ISSUE THREAD

**Issue by skodapetr** [rdk/p2rank#17]
Some documentation files use _txt_ extension although the seems to be written in markdown. For example [this file](https://github.com/rdk/p2rank/blob/develop/distro/test_data/readme.txt).

Why is not _md_ extension used everywhere? 
Also, it is not that in dist directory only txt is used as the root of that directory contains _md_ file.

**Comment by rdk** [comment]
_md_ is used for longer texts that can make use of formatting while _txt_ is used only for short notes about the purpose and content of the directory.  _txt_ files containing _md_ formatting should be renamed to _md_ (I'm not aware of any right now).
