### ISSUE TITLE
Spearmint and Python 3

### ISSUE THREAD

**Issue by skodapetr** [rdk/p2rank#19]
As the end of Python 2 support, have you tested Spearmint  with Python 3? Spearmint's repository 
 (from 2016) operates (in readme.md) with Python 2.7.

**Comment by rdk** [comment]
It doesn't look like Spearmint is ever going to be updated for Python 3, but I have integrated alternative optimizer https://github.com/josejimenezluna/pyGPGO which runs on Python 3 (see https://github.com/rdk/p2rank/blob/develop/misc/tutorials/hyperparameter-optimization-tutorial.md#optimization-with-pygpgo). 
Implemented on develop branch and will be released in 2.4 .
