### ISSUE TITLE
exception: Not enough training instances with class labels

### ISSUE THREAD

**Issue by skodapetr** [rdk/p2rank#21]
```
ERROR: hr.irb.fastRandomForest.FastRandomTree: Not enough training instances with class labels (required: 1, provided: 0)!
weka.core.WekaException: hr.irb.fastRandomForest.FastRandomTree: Not enough training instances with class labels (required: 1, provided: 0)!
```
It is not clear what went wrong, why and how to fix it.
Is it positive or negative .. was there no data, bad parameters used? How many instances were extracted from given data and if none why?

Tested using latest release 2.0.1.

**Comment by rdk** [comment]
Ths indicates that no ligands were detected in the training dataset and consequently no SAS points were labeled as positives.

Could be a problem in the dataset file or in the fact that you were using an old version.
Version on the main branch 2.0.1 probably does not support specifying relevant ligands by name yet.
For training new models please always use version from the develop branch.

Do you have the same problem when using version from the develop?

**Comment by rdk** [comment]
Do you still have this problem with the new version from develop?

**Comment by skodapetr** [comment]
This was related to the ions, I will recreate/re-open with data sample if this happens again.
