### ISSUE TITLE
PyMOL output file names are not quoted

### ISSUE THREAD

**Issue by davidhoksza** [rdk/p2rank#22]
When carrying out a prediction of a multichain protein via PrankWeb , the resulting PyMOL script does not work because the filename contains a coma and it is not quoted. 

```load data/pdbid_6lu7_A,C.ent.gz, protein```

needs to be changed to

```load "data/pdbid_6lu7_A,C.ent.gz", protein```.

Using a coma in filenames should be avoided as well.

**Comment by rdk** [comment]
Fixed on the develop branch.

Quotes have been added to all relevant places in PyMol output, but comas come from PrankWeb.
