### ISSUE TITLE
Fpocket in tutorial

### ISSUE THREAD

**Issue by skodapetr** [rdk/p2rank#25]
Is it necessary to mention historical reason and Fpocket in the ```training-tutorial.md``` ? I though p2rank provide better results and as a user, this information is not necessary for me making the tutorial harder to read.

**Comment by rdk** [comment]
I still do consider it important, at least until the change of P2Ranks default model and associated parameters. Othersise you might wonder why training P2Rank with default parameters will not give  as good results as presented in papers.

This is key:

> I recent versions it might be possible to achieve better results by training from whole protein surface in combination with class balancing techniques (see the next section).
> Note that default values of other parameters (related to feature extraction and classification results aggregation) were optimized for the case where `sample_negatives_from_decoys = true`.
> ... Their values may need to be optimized again for case of `sample_negatives_from_decoys = false`.
