### ISSUE TITLE
hyperparameter optimization tutorial

### ISSUE THREAD

**Issue by skodapetr** [rdk/p2rank#28]
In the hyperparameter optimization tutorial (```hyperparameter-optimization-tutorial.md```) there is only an example. It would be nice to a comprehensive list of all the values user can optimize. 

After reading the tutorial I do not know what I can put after ```-paramA``` , ```-paramB```. 
It is also not clear that ```paramA``` and ```paramA``` are name of the parameters and not cmd-line keywords.

In the ```Real example``` section it is not clear why the values in List expression are in extra braces. 
Why ```((protrusion.bfactor),(protrusion.bfactor.new_feature))``` instead of ```(protrusion.bfactor,protrusion.bfactor.new_feature)```. There is no explanation give.

Also, there is a paragraph in the braces, is it optional? Is it important? If it is extra information not needed right now it should not be there, if it is useful information it should be without braces,

Also in the last section (```Run optimization experiment```) you use ```-<param1>``` to denote parameter, this is inconsistent with the ```-paramA```  used before.

**Comment by rdk** [comment]
> In the hyperparameter optimization tutorial (hyperparameter-optimization-tutorial.md) there is only an example. It would be nice to a comprehensive list of all the values user can optimize.

You can optimize any number/boolean parameter. Comprehensive list with descriptions is in Params.groovy. I have added notes to the tutorial.

> After reading the tutorial I do not know what I can put after -paramA , -paramB. 

Format and few examples are included in the turorial. I have added some more examples.

>It is also not clear that paramA and paramA are name of the parameters and not cmd-line keywords.

Everything after `-` is a parameter.

> In the Real example section it is not clear why the values in List expression are in extra braces.
Why ((protrusion.bfactor),(protrusion.bfactor.new_feature)) instead of (protrusion.bfactor,protrusion.bfactor.new_feature). There is no explanation give.

That is just that P2Rank uses for list of lists. It was intended to distinguish list of strngs from list of single-valued lists. I guess it is not really necessary and can be changed in the implementation.

> Also, there is a paragraph in the braces, is it optional? Is it important? If it is extra information not needed right now it should not be there, if it is useful information it should be without braces,

Not sure what exactly you men. But I guess that is a stylistic choice. Information might be useful but not necessary.

> Also in the last section (Run optimization experiment) you use -<param1> to denote parameter, this is inconsistent with the -paramA used before.

Changed.

**Comment by skodapetr** [comment]
> > It is also not clear that paramA and paramA are name of the parameters and not cmd-line keywords.
> 
> Everything after `-` is a parameter.

Yep, but that should be stated in the tutorial.

> 
> > In the Real example section it is not clear why the values in List expression are in extra braces.
> > Why ((protrusion.bfactor),(protrusion.bfactor.new_feature)) instead of (protrusion.bfactor,protrusion.bfactor.new_feature). There is no explanation give.
> 
> That is just the particular syntax that P2Rank uses for list of lists. It was intended to distinguish list of strngs from list of single-valued lists. I guess it is not really necessary and can be changed in the implementation.

I have no issue with the syntax, just that I haven't found any information about it in the tutorial.

**Comment by rdk** [comment]
> Yep, but that should be stated in the tutorial.
I don't see how this is not clear. But you can include the note in the tutorial and send me a pull request.

> I have no issue with the syntax, just that I haven't found any information about it in the tutorial.
It is a tutorial for developers really, not every information on every detail will ever be there. But if you think it is crucial or valuable information you can extend the tutorial if you want.
