### ISSUE TITLE
failFast for conservation

### ISSUE THREAD

**Issue by skodapetr** [rdk/p2rank#37]
I used the command:
```
.\p2rank-develop\prank.bat traineval -t .\datasets\chen11.ds -e .\datasets\joined(mlig).ds -threads 4 -rf_trees 128 delete_models 0 -loop 1 -seed 42 -delete_vectors 0 -feature_importances 1 -failFast 1 -l conserv_cloud -extra_features 'conserv_cloud' -load_conservation 1 -load_conservation_paths 1  -conservation_dir .\..\conservation

```
in LOG file I see
```
[ERROR] ConservationScore - Score file doesn't exist [.\datasets\.\..\conservation\a.029.003.001_1rx0aA.hssp.hom.gz]
```
I would expect p2rank to fail with ```-failFast 1``` option in case of error, as now it seems like all is ok but in fact no conservation is loaded as the path is wrong.

Tested with f4c1e634087238f907bbab3a2391e4eec5faf0d4.

**Comment by rdk** [comment]
Fixed on develop branch and will be released in v2.3

`-fail_fast 1` mode was not always respected when running the program with multiple threads.
