### ISSUE TITLE
Log output change

### ISSUE THREAD

**Issue by skodapetr** [rdk/p2rank#39]
Is it possible to redirect log to stdout or stderr ? As by default many of the logs are stored in the {output}/run.log directory.

**Comment by rdk** [comment]
There are two parameters that control this:

- `log_to_console {0|1}`... write log messages to stderr
- log_to_file {0|1} ... write logs to `{output}/run.log`

Anyway, this is how it should work, but I had some issues with logging provider initialization before... so if it doesn't let me know. 
Caveat: if you are running P2Rank with prank.sh from binary distribution (i.e. from /distro/prank.sh), stderr is redirected to {install_dir}/log/prank.log .

**Comment by skodapetr** [comment]
Ok, I can do with a custom script file, thanks.
