### ISSUE TITLE
What are best practices to generating docking gridboxes from P2R points?

### ISSUE THREAD

**Issue by 5xx7xx** [rdk/p2rank#40]
Hello, I'm using P2R to aid autodock vina virtual screening and I was wondering how exactly should a grid box be derived from the points generated by P2R? Specifically, is containing all the points designated as "surface" of the pocket enough to catch all high affinity poses? Or should a margin of space be added around that, to facilitate poses which might be partially contained in the pocket but not entirely? If so, how big should the margin be?

(Btw, thank you for making this software, it's really quite wonderful.)

**Comment by rdk** [comment]
I would say it is a good idea to extend the size of the bounding box by a margin and the size of the margin depends on the size of the small molecule(s) you are trying to dock. I would use at least 1/2 of the ligand "length". P2Rank sometimes identifies only the hotspot in the centre of a binding site. You can try to find an empirical answer by looking at some dataset of protein ligand complexes with known ligand poses and running P2Rank predictions on it.

(You are welcome :) )

**Comment by 5xx7xx** [comment]
Thank you!
