### ISSUE TITLE
Java options unrecognized by OpenJDK 15

### ISSUE THREAD

**Issue by davidhoksza** [rdk/p2rank#44]
When trying to run the P2Rank with OpenJDK 15, I am getting

```
Unrecognized VM option 'CMSClassUnloadingEnabled'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit. 
```

The same with the second option (`UseConcMarkSweepGC`) when I remove `CMSClassUnloadingEnabled`. When I remove both `prank predict -f test_data/1fbl.pdb ` runs just fine.

**Comment by rdk** [comment]
Fixed on develop by removing the options. They are relevant only for Java 8 and not really necessary.
