### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by AndreaSoltes** [rdk/p2rank#55]
I was trying to train a new model on train dataset (holo4k_train.ds containing 3634 proteins) and validation dataset (holo4k_test.ds containing 409 proteins) (memory settings: $JAVA_OPTS -Xmx16G) using the following command:
./prank traineval -t p2rank-datasets/holo4k_train.ds -e p2rank-datasets/holo4k_test.ds -threads 4 -rf_trees 200 -delete_models 0 -loop 1 -seed 42
I got out of memory error (see run.log attached).. any idea how many Gs do I need?
[out_of_error.zip](https://github.com/rdk/p2rank/files/8803571/out_of_error.zip)

**Comment by rdk** [comment]
That's hard to say. 
Some tips how to reduce required memory for training are here https://github.com/rdk/p2rank/blob/develop/misc/tutorials/training-tutorial.md#raquired-memory-and-memorytime-trade-offs

The main factor in memory usage is how many trees are trained in parallel. 
You can try `-rf_threads 1` to train only 1 tree at a time. This will reduce required memory up to 4x but it will need 4x time.
