### ISSUE TITLE
installation not clear?

### ISSUE THREAD

**Issue by ghost** [rdk/p2rank#56]
Just came across P2Rank and interested to run it on a zipped folder containing protein conformations from a trajectory.
I  have pymol installed on the linux cluster and I did this:
#git clone https://github.com/rdk/p2rank.git

I see  a p2rank folder created.
What is the next step? Do I have to do a make install or how to run it on a test.pdb file?

Thanks

**Comment by rdk** [comment]
There are 2 ways how to install P2Rank: downloading a pre-built `.tar.gz` distribution from https://github.com/rdk/p2rank/releases (easier) or cloning a git repo and building from sources (better if you want to use the latest updates or train new models).

You have started with cloning a repo... so please try to follow steps here: https://github.com/rdk/p2rank#build-from-sources
Basically, the only necessary step is to run `./make.sh` and then you can run prediction either with `./prank.sh predict test.pdb` or `./distro/prank predict test.pdb`. Note that you need to have Java installed on the machine (JRE, version >= 8).

Let me know it it works.

**Comment by iitb33** [comment]
> There are 2 ways how to install P2Rank: downloading a pre-built `.tar.gz` distribution from https://github.com/rdk/p2rank/releases (easier) or cloning a git repo and building from sources (better if you want to use the latest updates or train new models).
> 
> You have started with cloning a repo... so please try to follow steps here: https://github.com/rdk/p2rank#build-from-sources Basically, the only necessary step is to run `./make.sh` and then you can run prediction either with `./prank.sh predict test.pdb` or `./distro/prank predict test.pdb`. Note that you need to have Java installed on the machine (JRE, version >= 8).
> 
> Let me know it it works.

Hi
After installing p2rank I ran it from the installation directory but I got these errors

command used 
`./prank.sh predict -f /home/loki/Desktop/p2rank/distro/test_data/1fbl.pdb`

Errors 
```
./prank.sh: line 9: local-env.sh: No such file or directory
Error: Could not find or load main class cz.siret.prank.program.Main
Caused by: java.lang.ClassNotFoundException: cz.siret.prank.program.Main
```
Could you help me resolving these errors?
Thanks

**Comment by iitb33** [comment]
Hi, I got this error after `./make.sh `

```
Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
...........10%............20%...........30%............40%...........50%............60%...........70%............80%...........90%............100%

Welcome to Gradle 7.5.1!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'p2rank'.
> Could not load compiled classes for build file '/home/loki/Desktop/tcs/downloads/p2rank/build.gradle' from cache.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
```

**Comment by rdk** [comment]
Hi @iitb33, 
what operating system and Java Virtual Machine are you using? Could you paste here an output of running `java -version` on your machine?

**Comment by iitb33** [comment]
operating system - `Ubuntu 20.04.5 LTS`

`java -version` output
```
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

**Comment by rdk** [comment]
Could you try to 
1. Paste here the output of command `echo $JAVA_HOME`
2. pull the latest changes on brench develop (there was one dependency that became unavailable and I had to change it)
3. build it by running ` ./gradlew -i clean assemble` 
...and attach the console output in case it fails?

**Comment by iitb33** [comment]
Hi @rdk 

1. output of command `echo $JAVA_HOME`

`/usr/lib/jvm/java-11-openjdk-amd64/bin/java`

2. I don't understand the second point. Can you elaborate?
3. Output of `./gradlew -i clean assemble`

```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-11-openjdk-amd64/bin/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by rdk** [comment]
You need to set up your
`JAVA_HOME` environment variable correctly. I guess the correct location in your case is `/usr/lib/jvm/java-11-openjdk-amd64/`.

You can try it by running the following:
```
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
```
and then rebuilding again.

**Comment by iitb33** [comment]
I did that and build it again but got the same error. one thing to note that I am not the root user of the system.  

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'p2rank'.
> Could not load compiled classes for build file '/home/loki/Desktop/tcs/p2rank/build.gradle' from cache.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
```

**Comment by rdk** [comment]
The fact that you are not root shouldn't be a problem. I just tried o build it as non root on the same version of ubuntu and java and it worked.

Did you agin get the exactly the same error "ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-11-openjdk-amd64/bin/java"?
If not could you repeat the 3 steps from my earlier comment exactly and attach the exact error message here?

By the way if you don't need the latest development version you can just download the latest release package that is already compiled. However, even for running P2Rank you need to have Java environment configured correctly.

**Comment by iitb33** [comment]
I am doing this with `sudo -s ` command

1. output of command `echo $JAVA_HOME`
`/usr/lib/jvm/java-11-openjdk-amd64/bin/java`

2. I don't understand the second point. Can you elaborate?
3. Output of `./gradlew -i clean assemble`

```
Initialized native services in: /root/.gradle/native
Initialized jansi services in: /root/.gradle/native
Removing 0 daemon stop events from registry
Starting a Gradle Daemon (subsequent builds will be faster)
Starting process 'Gradle build daemon'. Working directory: /root/.gradle/daemon/7.5.1 Command: /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=IN -Duser.language=en -Duser.variant -cp /root/.gradle/wrapper/dists/gradle-7.5.1-bin/7jzzequgds1hbszbhq3npc5ng/gradle-7.5.1/lib/gradle-launcher-7.5.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.5.1
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 4.601 secs.
The client will now receive all logging from the daemon (pid: 591575). The daemon log file: /root/.gradle/daemon/7.5.1/daemon-591575.out.log
Starting build in new daemon [memory: 512 MiB]
Using 8 worker leases.
Watching the file system is configured to be enabled if available
Now considering [/home/loki/Desktop/tcs/p2rank] as hierarchies to watch
File system watching is active
Starting Build
Settings evaluated using settings file '/home/loki/Desktop/tcs/p2rank/settings.gradle'.
Projects loaded. Root project using build file '/home/loki/Desktop/tcs/p2rank/build.gradle'.
Included projects: [root project 'p2rank']

> Configure project :
Evaluating root project 'p2rank' using build file '/home/loki/Desktop/tcs/p2rank/build.gradle'.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'p2rank'.
> Could not load compiled classes for build file '/home/loki/Desktop/tcs/p2rank/build.gradle' from cache.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```

Additionally I downloaded and extracted `p2rank_2.4.tar.gz` and ran the command `prank predict -f /home/loki/Desktop/1hkg.pdb` from the extracted folder.

I go this error message
```
Command 'prank' not found, but can be installed with:

sudo apt install prank

```

**Comment by rdk** [comment]
Closing an old issue. @iitb33 if you still have problems running P2Rank let me know.
