### ISSUE TITLE
[SUGGESTION] Release Binary Should Log To STDERR instead of to install directory

### ISSUE THREAD

**Issue by lilleswing** [rdk/p2rank#59]
In https://github.com/rdk/p2rank/blob/develop/distro/prank the program logs to a logfile, that is default inside the installation directory.  I believe this is the run-script distributed in the release tarball.

When installing this on HPC systems often the installation directory is not writable by the users running the software leading to errors. In the case that it *is* writable by users then there can be thrashing and race conditions in the logfile if multiple jobs are writing to it at once.

It might be better to distribute the version that logs to stdout instead of a logfile in the install directory.

**Comment by rdk** [comment]
Thanks for the suggestion. I happen to agree and wanted to change it for some time. 

It will be changed in the next release.
