### ISSUE TITLE
Possibility to retrieve protein sequence directly

### ISSUE THREAD

**Issue by lorenzoFabbri** [rdk/p2rank#6]
Hi,

I'm trying to use P2Rank inside my pipeline to retrieve the protein sequence of the putative binding site.
I'd like to know if there is the possibility to get the protein sequence other than the list of residue IDs. I'm trying to use BioPython but the sequence I get from it is shorter than the one in the PDB file. Right now I'm retrieving the sequence from the PDB file using some code I wrote but it should be an output of the program, I guess. Thanks.

Lorenzo

**Comment by rdk** [comment]
Hi Lorenzo,
Thank you for your interest in p2rank. Version 2.1-dev.1 (https://github.com/rdk/p2rank/releases/tag/2.1-dev.1) produces residues.csv file which contains a list of all residues. You can have a look if you are able to extract protein sequences from it in the format you need. If this doesn't help let me know.
