### ISSUE TITLE
Dataset contains invalid files

### ISSUE THREAD

**Issue by amarye** [rdk/p2rank#61]
I have followed your instruction for binary backage. But when I ran prank, I got error about dataset.
So could you help me please to fix this problem?
![Screenshot from 2022-11-30 11-49-48](https://user-images.githubusercontent.com/55770700/204703762-e6fe73ba-985b-47ff-a064-62082fc1f3d3.png)

**Comment by rdk** [comment]
If you run prediction directly on `pdb` or `cif` file, you need to use `-f` command line option.
So your command should be: `./prank.sh predict -f cyclin-D1.pdb`.

By the way, unsess you plan to train new P2Rank prediction models, I recommend using `prank` script in '/distro' directory to run basic predictions.
