### ISSUE TITLE
No SLF4J providers were found!

### ISSUE THREAD

**Issue by amarye** [rdk/p2rank#62]
I got this error. 
Could you please help me to solve this issue?
![Screenshot from 2022-12-01 16-46-10](https://user-images.githubusercontent.com/55770700/205007768-21518898-c77f-48d9-859c-6d40da928d8b.png)

**Comment by rdk** [comment]
Which version of P2Rank are you using?
Could you attach an output of commands `java -version` and `echo $JAVA_HOME`.

**Comment by amarye** [comment]
yeah, you are right. got it with thank

**Comment by rdk** [comment]
@amarye, does it work now? Do you know where was the problem?

**Comment by amarye** [comment]
yeah, it is working. The problem is with java path

**Comment by amarye** [comment]
thanks a lot
