### ISSUE TITLE
Different results compared to PrankWeb?

### ISSUE THREAD

**Issue by AlexLam37** [rdk/p2rank#70]
This is the same/related issue I've previously asked in the prankweb page however I thought it was useful to ask here as well.
https://github.com/cusbg/prankweb/issues/142#issue-2226798402

I am trying to use p2rank to predict pockets for a bunch of proteins but I noticed there are different results compared to the web server. I.e. if I go to the web server and use the "predicted structure" and input a uniprot ID, it seemingly gives different results compared to if I download the AF model from uniprot, and then run that on p2rank.

Similarly if I download the AF model and submit as custom structure to the web server, it gives same result as the standalone p2rank. 

Is the web server over/underestimating pocket probabilities? Please see below for an example using A0A644EZV9

Using "predicted structure" on prankweb
![image](https://github.com/rdk/p2rank/assets/166084931/ad76dfc7-fc93-4f47-baa6-12c6d4d95e82)

Using "custom structure" on prankweb, same results as running standalone p2rank
![image](https://github.com/rdk/p2rank/assets/166084931/faee5d09-24dd-4ea6-ab74-a45ea3c0959a)

**Comment by davidhoksza** [comment]
See the explanation at https://github.com/cusbg/prankweb/issues/142#issuecomment-2046043352 .

**Comment by rdk** [comment]
Closing since the question was answered in PrankWeb issue. If some confusion remains, let me know.
