### ISSUE TITLE
incomplete test_output

### ISSUE THREAD

**Issue by SusuSui** [rdk/p2rank#71]
Hi,
I tried running p2rank from bash. I added a pdb file to "test_data". However, for "test_output" I did not receive the "structure.pdb_predictions.csv", "structure.pdb_residues.csv". In the "visualizations"  I did receive the structure.pdb.pml. When I run the exact same file through PrankWeb I received them. Would you have any idea why it is like that?

Thanks in advance!

**Comment by rdk** [comment]
Hi, 
Which version of P2Rank are you using? Is it downloaded from https://github.com/rdk/p2rank/releases or built from sources?

**Comment by SusuSui** [comment]
It was downloaded from that url and the version is the latest 2.4.1

**Comment by rdk** [comment]
Unfortunately I wasn't able to reproduce it. Could you provide more details? 
* What operating system are you running on?
* What is the exact command that produces this behaviour?
* If you can, provide the structure file itself

**Comment by SusuSui** [comment]
Hi I tried running it on a different machine and it worked there. That means there has to be some internal problem with my machine which is not connected to the program. I will try to resolve it. Anyways thank you for the help!
