### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by eventfulsean** [rdk/p2rank#8]
Hi!

I'm getting the following error when running prank:

ERROR: No signature of method: cz.siret.prank.program.routines.Experiments.single.ds() is applicable for argument types: () values: []
groovy.lang.MissingMethodException: No signature of method: cz.siret.prank.program.routines.Experiments.single.ds() is applicable for argument types: () values: []

What are the pre-requisites for the precompiled version?

Thanks

**Comment by rdk** [comment]
What is the exact command you running / how can I reproduce it?

**Comment by rdk** [comment]
It seems that the program was executed with command "./prank single.ds" instead of correct "./prank predict single.ds".
